version: '3.8'


services:
  cla-end-to-end:
    build: .
    volumes:
      - .:/behave
    ports:
      - "8002:80"
    depends_on:
      - clabackend
      - clafrontend
      - seleniumchrome

  seleniumchrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    ports:
      - "5900:5900"
      - "4444:4444"
    shm_size: 2g

  clafrontend:
    image: ${CLA_FRONTEND_IMAGE:-754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-get-access/cla_frontend:master}
    ports:
      - "8001:80"
    depends_on:
      - clabackend
    environment:
      ENV: local
      DEBUG: "True"
      SECRET_KEY: CHANGE_ME
      BACKEND_BASE_URI: http://clabackend:8000
      CALL_CENTRE_CLIENT_ID: b4b9220ffcb11ebfdab1
      CALL_CENTRE_SECRET_ID: 2df71313bdd38a2e1b815015e1b14387e7681d41
      CLA_PROVIDER_CLIENT_ID: 59657ed22d980251cdd3
      CALL_PROVIDER_SECRET_ID: 0494287c65bdf61d29f0eeed467ec8e090f0d80f
      SOCKETIO_SERVER_URL: http://clafrontend:8000/socket.io
      SOCKETIO_SERVICE_URL: clafrontend:8000/socket.io/
      OS_PLACES_API_KEY: DUMMY_KEY

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cla_backend

  clabackend:
    image: ${CLA_BACKEND_IMAGE:-754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-get-access/cla_backend:master}
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      ENV: local
      DEBUG: "True"
      SECRET_KEY: CHANGE_ME
      DB_NAME: cla_backend
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      BACKEND_ENABLED: "True"
      LOAD_TEST_DATA: "True"
      ADMIN_PASSWORD: cla_admin
      ALLOWED_HOSTS: "*"