version: '3.8'

services:
  cla-end-to-end:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  clafrontend:
    build: https://github.com/ministryofjustice/cla_frontend.git#master
  clabackend:
    build: https://github.com/ministryofjustice/cla_backend.git#master