version: '3.2'
services:
  cla_public:
    image: ${CLA_BACKEND_IMAGE:-754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-get-access/cla_public:master}
    ports:
      - target: 80
        published: 5000
        protocol: tcp
        mode: host
    environment:
      HOST_NAME: "0.0.0.0"
      SECRET_KEY: CHANGE_ME
      BACKEND_BASE_URI: http://cla-backend:80
      CLA_ENV: dev
      ZENDESK_API_USERNAME: ""
      ZENDESK_API_TOKEN: ""
      SMTP_HOST: ""
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      SENTRY_DSN: ""
      LAALAA_API_HOST: "https://laa-legal-adviser-api-production.cloud-platform.service.justice.gov.uk"
      MOJ_GA_ID: "UA-XXXXXXXX-X1"
      GDS_GA_ID: "UA-XXXXXXXX-X2"
