name: Pull images
description: Pull ECR images

inputs:
  ECR_ROLE_TO_ASSUME:
    required: true
    description: ECR role to assume
  ECR_REGION:
    required: true
    description: ECR region
  SERVICE_NAME:
    required: true
    description: Docker service to pull image for
  DOCKER_COMPOSE_FILE_PATH:
    required: true
    description: Path to docker compose file

runs:
  using: composite
  steps:
    - name: AWS Auth
      uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 #--6.1.0
      with:
        role-to-assume: ${{ inputs.ECR_ROLE_TO_ASSUME }}
        aws-region: ${{ inputs.ECR_REGION }}
        role-session-name: test

    - name: Docker login
      uses: aws-actions/amazon-ecr-login@19d944daaa35f0fa1d3f7f8af1d3f2e5de25c5b7 #--2.1.4

    - name: Pull cla backend image
      run: |
        docker compose -f ${{ inputs.DOCKER_COMPOSE_FILE_PATH }} pull ${{ inputs.SERVICE_NAME}}
      shell: bash
