version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  orb-tools: circleci/orb-tools@10.0

jobs:
  behave:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install compatible docker-compose
          command: pip install docker-compose==1.27.4
      - run:
          name: Authenticate with awscli
          command: |
            pip install awscli
            login="$(aws ecr get-login --region eu-west-2 --no-include-email)"
            ${login}
      - run:
          name: Build / pull Docker images
          command: |
            cd behave
            docker-compose pull
            docker-compose build
      - run:
          name: Check services are up
          command: |
            cd behave
            docker-compose run start_applications
            docker-compose exec clabackend bin/create_db.sh
            docker-compose exec clabackend python manage.py loaddata test_special_provider_case.json
      - run:
          name: Run behave tests
          command: |
            cd behave
            docker-compose run --name cla-end-to-end cla-end-to-end
      - run:
          name: Copy artifacts
          command: |
            mkdir -p /tmp/feature_errors
            docker cp cla-end-to-end:behave_local ../../../tmp/feature_errors
          when: always
      - store_artifacts:
          path: /tmp/feature_errors

workflows:
  build:
    jobs:
      - aws-ecr/build-and-push-image:
          name: Build and push
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
      - aws-ecr/build-and-push-image:
          name: Build and push latest tag
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "latest"
          filters:
            branches:
              only:
                - main
      - orb-tools/publish-dev:
          name: publish_dev_orb
          attach-workspace: false
          checkout: true
          orb-name: ministryofjustice/cla-end-to-end-tests
          orb-path: orb.yml
          publish-token-variable: CLI_TOKEN_TEST
          context:
            - test_create_orb
      - orb-tools/dev-promote-prod-from-commit-subject:
          name: publish_production_orb
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          orb-name: ministryofjustice/cla-end-to-end-tests
          publish-token-variable: CLI_TOKEN_TEST
          publish-version-tag: false
          requires:
            - publish_dev_orb
          context:
            - test_create_orb
      - behave