version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.3.0

workflows:
  build:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "latest"
          # filters:
            # branches:
              # only:
                # - main