#!/bin/sh -eu

safe_git_branch=${CIRCLE_BRANCH//\//-}
if [ "$CIRCLE_BRANCH" == "master" ]; then
  export TARGET_TAGS="$safe_git_branch,latest"
else
  export TARGET_TAGS="$safe_git_branch,$CIRCLE_SHA1"
fi
