version: '3.9'


services:
  start_applications:
    image: jwilder/dockerize
    command: >
      -wait tcp://clafrontend:8000
      -wait tcp://clasocketserver:8005
      -wait tcp://clabackend:8000
      -wait tcp://clapublic:8000
      -wait tcp://fala:8000
      -wait tcp://seleniumchrome:4444
      -wait-retry-interval 10s
      -timeout 180s
    depends_on:
      - clapublic
      - clafrontend
      - clabackend
      - seleniumchrome
      - clasocketserver
      - fala
      - prev_db

  cla-end-to-end:
    container_name: cla-end-to-end
    build:
      context: .
    volumes:
      - .:/behave_local
      - ./data:/data
    environment:
      A11Y_ENABLED: ${A11Y_ENABLED:-false}
      BROWSER: chrome
      ARTIFACTS_DIRECTORY: /behave_local
      DATA_DIRECTORY: /data
      CLA_E2E_PUBLIC_URL: ${CLA_E2E_PUBLIC_URL:-http://clapublic:8000}
      CLA_E2E_BACKEND_URL: ${CLA_E2E_BACKEND_URL:-http://clabackend:8000}
      CLA_E2E_FRONTEND_URL: ${CLA_E2E_FRONTEND_URL:-http://clafrontend:8000}
      CLA_E2E_FALA_URL: ${CLA_E2E_FALA_URL:-http://fala:8000}
      CLA_E2E_SELENIUM_WEB_DRIVER_URL: ${CLA_E2E_SELENIUM_WEB_DRIVER_URL:-http://seleniumchrome:4444/wd/hub}
      CALL_CENTRE_CLIENT_ID: b4b9220ffcb11ebfdab1
      CALL_CENTRE_SECRET_ID: 2df71313bdd38a2e1b815015e1b14387e7681d41
      CALL_CENTRE_TEST_USER: test_operator
      CLA_PROVIDER_CLIENT_ID: 59657ed22d980251cdd3
      CLA_PROVIDER_SECRET_ID: 0494287c65bdf61d29f0eeed467ec8e090f0d80f

  seleniumchrome:
    deploy:
      resources:
        limits:
          memory: 2gb
    image: selenium/standalone-chrome:latest
    user: root
    hostname: chrome
    ports:
      - "5900:5900"
      - "4444:4444"
    shm_size: 2g
    volumes:
      - ./data:/data

  clasocketserver:
    image: ${CLA_SOCKET_SERVER_IMAGE:-754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-get-access/cla_frontend_socket_server:master}
    environment:
      SITE_HOSTNAME: clasocketserver

  clafrontend:
    image: ${CLA_FRONTEND_IMAGE:-754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-get-access/cla_frontend:master}
    ports:
      - "8011:8000"
    depends_on:
      - clabackend
      - clasocketserver
    environment:
      ENV: local
      DEBUG: "True"
      SECRET_KEY: CHANGE_ME
      BACKEND_BASE_URI: http://clabackend:8000
      CALL_CENTRE_CLIENT_ID: b4b9220ffcb11ebfdab1
      CALL_CENTRE_SECRET_ID: 2df71313bdd38a2e1b815015e1b14387e7681d41
      CLA_PROVIDER_CLIENT_ID: 59657ed22d980251cdd3
      CLA_PROVIDER_SECRET_ID: 0494287c65bdf61d29f0eeed467ec8e090f0d80f
      SOCKETIO_SERVER_URL: http://clasocketserver:8005/socket.io
      SOCKETIO_SERVICE_URL: clasocketserver:8005/socket.io/
      OS_PLACES_API_KEY: ${OS_PLACES_API_KEY:-CHANGE_ME}
      GA_ID: ${GA_ID:-CHANGE_ME}
      GA_DOMAIN:  ${GA_DOMAIN:-localhost}
      SITE_HOSTNAME: clasocketserver
      STATIC_FILES_BACKEND: local
      ALLOWED_HOSTS: "*"
      SESSION_COOKIE_SECURE: "False"

  db:
    image: postgres:11.18-alpine
    ports:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cla_backend
      POSTGRES_HOST_AUTH_METHOD: trust

  prev_db:
    image: postgres:11.18-alpine
    ports:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cla_backend
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data:/data

  clabackend:
    image: ${CLA_BACKEND_IMAGE:-754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-get-access/cla_backend:master}
    ports:
      - "8010:8000"
    depends_on:
      - db
    environment:
      ENV: local
      DEBUG: "True"
      SECRET_KEY: CHANGE_ME
      DB_NAME: cla_backend
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      BACKEND_ENABLED: "True"
      LOAD_SEED_DATA: "True"
      LOAD_TEST_DATA: "True"
      LOAD_END_TO_END_FIXTURES: "True"
      ADMIN_USER: cla_admin
      STATIC_FILES_BACKEND: local
      ADMIN_PASSWORD: cla_admin
      ALLOWED_HOSTS: "*"

  clapublic:
    image: ${CLA_PUBLIC_IMAGE:-754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-get-access/cla_public:master}
    ports:
      - "8012:8000"
    environment:
      HOST_NAME: "clapublic"
      SECRET_KEY: CHANGE_ME
      BACKEND_BASE_URI: http://clabackend:8000
      CLA_ENV: dev
      ZENDESK_API_USERNAME: ""
      ZENDESK_API_TOKEN: ""
      SMTP_HOST: ""
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      RAVEN_CONFIG_DSN: ""
      RAVEN_CONFIG_SITE: ""
      SENTRY_DSN: ${SENTRY_DSN:-}
      LAALAA_API_HOST: https://laa-legal-adviser-api-staging.apps.live-1.cloud-platform.service.justice.gov.uk
      MOJ_GA_ID: "UA-XXXXXXXX-X1"
      GDS_GA_ID: "UA-XXXXXXXX-X2"
      GOOGLE_MAPS_API_KEY: AIzaSyBVsZmfkiRFNNMJnPraN_8sBW3Dj-BFFNs
      OS_PLACES_API_KEY: ${OS_PLACES_API_KEY:-CHANGE_ME}
    depends_on:
      - clabackend

  fala:
    image: ${FALA_IMAGE:-754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-get-access/fala:master}
    ports:
      - "8013:8000"
    environment:
      HOST_NAME: "fala"
      SECRET_KEY: CHANGE_ME
      LAALAA_API_HOST: https://laa-legal-adviser-api-staging.apps.live-1.cloud-platform.service.justice.gov.uk
      CLA_ENV: dev