# Workflow: SCA ⚡️
# Description:
#   Scheduled and on-demand Security Composition Analysis run.
#   - Triggers: daily cron, pull/ push to main, workflow dispatch, branch protection rule.
#   - Environment and timezone shared across jobs.
# Jobs:
#   - setup: Prepares environment metadata.
#   - sca: Checks out repo, installs node, runs npm ci, executes ministryofjustice/sca action with dependency review configuration.

name: SCA ⚡️
run-name: Software Composition Analysis ⚡️

on:
  schedule:
    - cron: "0 0 * * *"

  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]

  workflow_dispatch:
  branch_protection_rule:

permissions: {}

env:
  environment: base
  timezone: ${{ vars.TIMEZONE }}

jobs:
  setup:
    name: Infrastructure 🔧
    runs-on: ["ubuntu-latest"]
    outputs:
      environment: ${{ env.environment }}
      timezone: ${{ env.timezone }}
    steps:
      - name: Environment 🧪
        run: echo "Environment set to ${{ env.environment }}"

      - name: Timezone 🌐
        run: echo "Timezone set to ${{ env.timezone }}"
  sca:
    permissions:
      contents: write
      pull-requests: write
      issues: write
      security-events: write
      actions: read

    name: Execute ⚙️
    runs-on: ["ubuntu-latest"]
    needs: setup
    environment:
      name: ${{ needs.setup.outputs.environment }}

    steps:
      - name: Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: ⚡️ SCA
        uses: ministryofjustice/devsecops-actions/sca@f965eb1771ec66cfc41d7d57dc607fa6dfbc10ed # v1.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Mandatory
          dependency-review-config-file: "./.github/dependency-review-config.yml" # Optional
