name: Build and run Snyk scan on Docker Image

on:
  pull_request:

jobs:
  build-and-scan:
    name: Build Image and Run Snyk Scan
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write  

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Generate image URI
        id: meta
        run: |
          IMAGE_URI="end-to-end-test"
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build \
            -t "${{ steps.meta.outputs.image_uri }}" \
            -f behave/Dockerfile \
            behave

      - name: Install Snyk CLI
        uses: snyk/actions/setup@9adf32b1121593767fc3c057af55b55db032dc04

      - name: Obtain short-lived Snyk token
        id: snyk-auth
        uses: ministryofjustice/laa-reusable-github-actions/.github/actions/snyk-auth@6db001458db30ae747d9eb8eb25707ce52b359bc
        with:
          client_id: ${{ secrets.SNYK_CLIENT_ID }}
          client_secret: ${{ secrets.SNYK_CLIENT_SECRET }}

      - name: Set Snyk token
        run: echo "SNYK_TOKEN=${{ steps.snyk-auth.outputs.token }}" >> $GITHUB_ENV

      - name: Scan container image
        env:
          IMAGE_URI: ${{ steps.meta.outputs.image_uri }}
        run: |
          mkdir -p sarif

          snyk container test "$IMAGE_URI" \
            --severity-threshold=high \
            --sarif-file-output=sarif/snyk.sarif

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sarif/snyk.sarif