name: Release on Merge

on:
  pull_request:
    types: [closed]

jobs:
  release:
    if: github.event.pull_request.merged == true &&
        github.event.pull_request.base.ref == 'main'

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          fetch-depth: 0

      - name: Bump version
        id: version
        uses: paulhatch/semantic-version@9f72830310d5ed81233b641ee59253644cd8a8fc #v6.0.2
        with:
          major_pattern: "BREAKING CHANGE"
          minor_pattern: "feat"
          version_format: "${major}.${minor}.${patch}"

      - name: Create Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda #v3.0.0
        with:
          tag_name: v${{ steps.version.outputs.version }}
          generate_release_notes: true