name: Workflow

on:
  pull_request:

permissions:
  contents: read

jobs:
# ---------------------------------------------------------- build (new) -----
  pull-images:
    name: Pull images
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name:  Pull Cla Frontend image
        uses: ./.github/actions/pull-image
        with:
          ECR_ROLE_TO_ASSUME: ${{ secrets.CLA_FRONTEND_ECR_ROLE_TO_ASSUME}}
          ECR_REGION: ${{ vars.CLA_FRONTEND_ECR_REGION }}
          SERVICE_NAME: clafrontend
          DOCKER_COMPOSE_FILE_PATH: ./behave/docker-compose.yml
