name: Workflow

on:
  pull_request:

permissions:
  contents: read

jobs:
# ---------------------------------------------------------- build (new) -----
  pull-images:
    name: Pull images
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name:  Set up AWS credentials
        id: ecr_step
        uses: ministryofjustice/laa-reusable-github-actions/.github/actions/ecr-auth@main
        with:
          ecr_region: ${{ vars.ECR_REGION }}
          ecr_role: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          role-session-name: laa-cla-end-to-end
      - name: Pull cla_frontend images
        run: docker compose -f ./behave/docker-compose.yml pull clafrontend
        env:
          # Use the output from your composite action
          ECR_REGISTRY: ${{ steps.ecr_step.outputs.image_registry }}


